### ISSUE TITLE
Suspicious Warning in Jenkins 

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/jenkins-server-notification-plugin#13]
I get the following warning multiple times (in the docker log of the jenkins container). Is that in any way critical?

Short Excerpt:
```
2021-07-19 11:45:40.090+0000 [id=10443] INFO    o.j.p.workflow.job.WorkflowRun#finish: PROGRAMMING21****/PROGRAMMING21****-SOLUTION #6 completed: SUCCESS
jenkins_1     | 2021-07-19 11:45:40.133+0000 [id=10443] WARNING o.j.p.w.cps.CpsFlowExecution#notifyListeners
jenkins_1     | java.lang.UnsupportedOperationException: Refusing to marshal de.tum.in.ase.parser.domain.Report for security reasons; see https://jenkins.io/redirect/class-filter/

```

Longer Excerpt:

```
jenkins_1     | 2021-07-19 07:08:46.598+0000 [id=8613]  WARNING o.j.p.w.cps.CpsFlowExecution#notifyListeners
jenkins_1     | java.lang.UnsupportedOperationException: Refusing to marshal de.tum.in.ase.parser.domain.Report for security reasons; see https://jenkins.io/redirect/class-filter/
jenkins_1     |         at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:540)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
jenkins_1     |         at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
jenkins_1     | Caused: java.lang.RuntimeException: Failed to serialize de.tum.in.www1.jenkins.notifications.model.TestResults#staticCodeAnalysisReports for class de.tum.in.www1.jenkins.notifications.model.TestResults
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
jenkins_1     |         at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
jenkins_1     |         at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
jenkins_1     |         at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
jenkins_1     |         at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
jenkins_1     |         at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
jenkins_1     | Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
jenkins_1     |         at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
jenkins_1     |         at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
jenkins_1     |         at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
jenkins_1     |         at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
jenkins_1     |         at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
jenkins_1     |         at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
jenkins_1     |         at com.thoughtworks.xstream.XStream.marshal(XStream.java:1278)
jenkins_1     |         at com.thoughtworks.xstream.XStream.marshal(XStream.java:1267)
jenkins_1     |         at com.thoughtworks.xstream.XStream.toXML(XStream.java:1240)
jenkins_1     |         at hudson.XmlFile.write(XmlFile.java:195)
jenkins_1     | Caused: java.io.IOException
jenkins_1     |         at hudson.XmlFile.write(XmlFile.java:202)
jenkins_1     |         at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:30)
jenkins_1     |         at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1210)
jenkins_1     |         at hudson.BulkChange.commit(BulkChange.java:98)
jenkins_1     |         at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1485)
jenkins_1     |         at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:489)
jenkins_1     |         at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
jenkins_1     |         at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
jenkins_1     |         at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
jenkins_1     |         at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
jenkins_1     |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jenkins_1     |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins_1     |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1     |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1     |         at java.lang.Thread.run(Thread.java:748)
........

```

**Comment by krusche** [comment]
The error looks like an issue to me. Do you know if the result is still send to Artemis and received correctly?
The question would be if only one issue cannot be serialized or if the whole REST call fails.

It would also be interesting which version of the Jenkins plugin you are using

**Comment by dfuchss** [comment]
Actually, so far everything seems to work. But maybe you should check whether this error is also present in your test systems
